import { Inter, Titillium_Web, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { WalletProvider } from "@/context/useWallet";
import { CourseProvider } from "@/context/useCourse";
import { AuthProvider } from "@/context/useAuth";
import { PoolProvider } from "@/context/usePool";
import { UserProvider } from "@/context/useData";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const titilliumWeb = Titillium_Web({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-titilliumWeb",
  weight: ["400", "700"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const relayUrls = [
//   "wss://relay.damus.io",
//   "wss://relay.snort.social",
//   "wss://nostr-pub.wellorder.net",
//   "wss://relay.nostr.ch",
//   "wss://nostr.jcloud.es"
// ];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${titilliumWeb.className} ${robotoMono.className} `}
      >
        <UserProvider>
          <AuthProvider>
            <PoolProvider>
              <WalletProvider>
                <CourseProvider>{children}</CourseProvider>
              </WalletProvider>
            </PoolProvider>
          </AuthProvider>
        </UserProvider>
      </body>
    </html>
  );
}
